In [1]:
import numpy as np

In [8]:
## Creating numpy arrays manually 
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape, arr.dtype)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.shape, arr2.dtype)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, type(arr2D), arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,) int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,) <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [21]:
## Creating numoy arrays with functions
arr1 = np.zeros(5, dtype="int64")
print(arr1)

arr2 = np.ones(5, dtype =  "int64")
print(arr2)

arr3 = np.full(5, 100)
print(arr3)

arr4 = np.eye(3)
print(arr4)

arr5 = np.arange(0,11,2)
print(arr5)

arr6 = np.linspace(1,100,5)
print(arr6)

[0 0 0 0 0]
[1 1 1 1 1]
[100 100 100 100 100]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  2  4  6  8 10]
[  1.    25.75  50.5   75.25 100.  ]


In [22]:
## Properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(3, 3)
9
int64
2


In [27]:
## Operation on numpy arrays
arr = np.array([[1,2],[4,5],[6,7]])
print(arr, arr.shape)

reshaped = arr.reshape(2,3)
print(reshaped, reshaped.shape)

[[1 2]
 [4 5]
 [6 7]] (3, 2)
[[1 2 4]
 [5 6 7]] (2, 3)
