In [2]:
import numpy as np

In [6]:
## Indexing

arr = np.array([1,2,3,4,5])
idx = [0,2,3]
print(arr[0])
print(arr[3])
print(arr[idx])


1
4
[1 3 4]


In [5]:
## Indexing 2D arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][2])
print(arr[1][2])


3
6


In [7]:
## Boolean Indexing
arr = np.array([1,2,3,4,5,6])
print(arr[arr>2])

[3 4 5 6]


In [9]:
## Slicing 
arr = np.array([1,2,3,4,5,6])
print(arr[1:3])
print(arr[2:5])

[2 3]
[3 4 5]


In [17]:
## Slicing ##

py_list = [1,2,3,4,5]
sub_list = py_list[2:5]
print(sub_list)
sub_list[0] = 100
print(sub_list)
print(py_list)

## For arrays 
num_arr = np.array([1,2,3,4,5])
sub_arr = num_arr[2:5]
print(sub_arr)
sub_arr[0] = 100
print(sub_arr)
print(num_arr)

[3, 4, 5]
[100, 4, 5]
[1, 2, 3, 4, 5]
[3 4 5]
[100   4   5]
[  1   2 100   4   5]
