In [2]:
import numpy as np 

In [14]:
## Multi dimensional arrays 
## 2D Arrays
np_array_2D = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(np_array_2D)

sum_of_columns = np.sum(np_array_2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(np_array_2D, axis = 1)
print(sum_of_rows)

print(np_array_2D[0:3, 2:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[18 21 24 27 30]
[15 40 65]
[[ 3]
 [ 8]
 [13]]


In [9]:
## 3D Arrays 
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D, arr3D.shape)

print(arr3D[0,2,0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
5
