In [1]:
import numpy as np

In [6]:
## Vectorization ## 

arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr + arr2) ## ADD TWO ARRAYS 
print(arr**2) ## TAKE POWER OF 2 FOR EACH ELEMENT IN THE ARRAY
print(arr+2) ## ADD TW0 TO EACH ELEMENT IN THE ARRAY 

[ 7  9 11 13 15]
[ 1  4  9 16 25]
[3 4 5 6 7]


In [9]:
## Vector Normalization ##
arr = np.array([[1,2,3],[4,5,6]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr - mean)/std_dev
print(normalized_arr)
print(mean)
print(std_dev)

[[-1.46385011 -0.87831007 -0.29277002]
 [ 0.29277002  0.87831007  1.46385011]]
3.5
1.707825127659933


In [28]:
## Mathematics functions ##

arr = np.array([1,2,3,5,4])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.median(arr))
print(np.std(arr))
print(np.mean(arr))
print(np.var(arr))
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.sort(arr))
print(np.unique(arr))
print(np.abs(arr))
print(np.round(3,14))
print(np.ceil(3.14)) ## round off to the upper value
print(np.floor(3.14)) ## round of to the lower value

15
120
1
5
0
3
3.0
1.4142135623730951
3.0
2.0
[ 1  4  9 25 16]
[1.         1.41421356 1.73205081 2.23606798 2.        ]
[  1   8  27 125  64]
[0.         0.69314718 1.09861229 1.60943791 1.38629436]
[0.         0.30103    0.47712125 0.69897    0.60205999]
[0.         1.         1.5849625  2.32192809 2.        ]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 5 4]
3
4.0
3.0
